tillzy-countzy/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles
  resources :counter

  root 'counter#new'

end

tillzy-countzy/app/models/article.rb
class Article < ActiveRecord::Base
end

tillzy-countzy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tillzy-countzy/app/controllers/counter_controller.rb
class CounterController < ApplicationController
  def show
    @counter = counter.find(params[:id])
  end

  def new
  end

  # snippet for brevity
end

tillzy-countzy/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

tillzy-countzy/app/helpers/application_helper.rb
module ApplicationHelper
end

tillzy-countzy/app/helpers/articles_helper.rb
module ArticlesHelper
end

tillzy-countzy/app/helpers/counter_helper.rb
module CounterHelper
end

tillzy-countzy/app/helpers/welcome_helper.rb
module WelcomeHelper
end

tillzy-countzy/app/views/articles/new.haml.erb
%h1
  new article

tillzy-countzy/app/views/articles/new.html.erb
<h1>new article</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

tillzy-countzy/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

tillzy-countzy/app/views/counter/new.html.haml
/ till count form
%form#msform
  / fieldsets
  %fieldset
    %h2.fs-title Till Count
    %h3.fs-subtitle Enter Coins by Weight
    %input#e.in{:onkeyup => "converte('e'); getItems('total')", :placeholder => "2 Euro (g)"}/
    %input#ee.out{:onkeyup => "converte('ee')", :name => "output", :value => "0"}/
    %input#f.in{:onkeyup => "convertf('f'); getItems('total')", :placeholder => "1 Euro (g)"}/
    %input#ff.out{:onkeyup => "converte('ff')", :name => "output", :value => "0"}/
    %input#g.in{:onkeyup => "convertg('g'); getItems('total')", :placeholder =>".50 cent (g)"}/
    %input#gg.out{:onkeyup => "convertg('gg')", :name => "output", :value => "0"}/
    %input#h.in{:onkeyup => "converth('h'); getItems('total')", :placeholder => ".20 cent (g)"}/
    %input#hh.out{:onkeyup => "converth('hh')", :name => "output", :value => "0"}/
    %input#i.in{:onkeyup => "converti('i'); getItems('total')", :placeholder => ".10 cent (g)"}/
    %input#ii.out{:onkeyup => "converti('ii')", :name => "output", :value => "0"}/
    %input#j.in{:onkeyup => "convertj('j'); getItems('total')", :placeholder => ".05 cent (g)"}/
    %input#jj.out{:onkeyup => "convertj('jj')", :name => "output", :value => "0"}/
    %input#k.in{:onkeyup => "convertk('k'); getItems('total')", :placeholder => ".02 cent (g)"}/
    %input#kk.out{:onkeyup => "convertk('kk')", :name => "output", :value => "0"}/
    %input#l.in{:onkeyup => "convertl('l'); getItems('total')", :placeholder => ".01 cent (g)"}/
    %input#ll.out{:onkeyup => "convertl('ll')", :name => "output", :value => "0"}/
    .total-line
    %input#x.out{:onkeyup => "getItems('total')",:placeholder => "Add to Total", :name => "output", :value => "0"}
    %input#tot{:onkeyup => "getItems('total')", :value => "0"}/




  / %fieldset
  /   %h2.fs-title Social Profiles
  /   %h3.fs-subtitle Your presence on the social network
  /   %input{:name => "twitter", :placeholder => "Twitter", :type => "text"}/
  /   %input{:name => "facebook", :placeholder => "Facebook", :type => "text"}/
  /   %input{:name => "gplus", :placeholder => "Google Plus", :type => "text"}/
  /   %input.previous.action-button{:name => "previous", :type => "button", :value => "Previous"}/
  /   %input.next.action-button{:name => "next", :type => "button", :value => "Next"}/
  / %fieldset
  /   %h2.fs-title Personal Details
  /   %h3.fs-subtitle We will never sell it
  /   %input{:name => "fname", :placeholder => "First Name", :type => "text"}/
  /   %input{:name => "lname", :placeholder => "Last Name", :type => "text"}/
  /   %input{:name => "phone", :placeholder => "Phone", :type => "text"}/
  /   %textarea{:name => "address", :placeholder => "Address"}
  /   %input.previous.action-button{:name => "previous", :type => "button", :value => "Previous"}/
  /   %input.submit.action-button{:name => "submit", :type => "submit", :value => "Submit"}/




<script>
function converte(eurotwo) {
if (eurotwo == "e") {
ee = document.getElementById("e").value / 8.5 * 2;
document.getElementById("ee").value = Math.round(ee);
}
}

function convertf(euroone) {
if (euroone == "f") {
ff = document.getElementById("f").value / 7.5;
document.getElementById("ff").value = Math.round(ff);
}
}

function convertg(eurofifty) {
if (eurofifty == "g") {
gg = document.getElementById("g").value / 7.80;
document.getElementById("gg").value = (Math.round(gg) * .50) .toFixed(2);
}
}

function converth(eurotwent) {
if (eurotwent == "h") {
hh = document.getElementById("h").value / 5.74;
document.getElementById("hh").value = (Math.round(hh) * .20).toFixed(2);
}
}

function converti(euroten) {
if (euroten == "i") {
ii = document.getElementById("i").value / 4.10;
document.getElementById("ii").value = (Math.round(ii) * .10).toFixed(2);
}
}

function convertj(eurofive) {
if (eurofive == "j") {
jj = document.getElementById("j").value / 3.92;
document.getElementById("jj").value = (Math.round(jj) * .05).toFixed(2);
}
}

function convertk(eurotwocent) {
if (eurotwocent == "k") {
kk = document.getElementById("k").value / 3.06 * 2;
document.getElementById("kk").value = (Math.round(kk) * .02).toFixed(2);
}
}

function convertl(euroonecent) {
if (euroonecent == "l") {
ll = document.getElementById("l").value / 2.30 * 1;
document.getElementById("ll").value = (Math.round(ll) * .01).toFixed(2);
}
}

function getItems()
{
var items = document.getElementsByClassName("out");
var itemCount = items.length;
var total = 0;
for(var i = 0; i < itemCount; i++)
{
total = total + parseFloat(items[i].value);
}
document.getElementById('tot').value = total.toFixed(2);
}
</script>

tillzy-countzy/app/views/counter/show.html.haml
%p
  %strong Title:
  = @article.title
%p
  %strong Text:
  = @article.text

tillzy-countzy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TillzyCountzy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>

tillzy-countzy/app/views/welcome/index.html.haml
.hero{:style => "background-image: url(https://s-media-cache-ak0.pinimg.com/736x/a5/0d/34/a50d3448f5dc127bd8ad502d038de920.jpg"}
  .hero__content.font-set
    %h1 Welcome to Till Count
    %a.btn{:href => "counter/new"} begin